<?php

namespace dafire\oauth_server\lib;

use OAuth2\ClientAssertionType\ClientAssertionTypeInterface;
use OAuth2\ScopeInterface;
use OAuth2\TokenType\TokenTypeInterface;

class Server extends \OAuth2\Server {
    public function __construct(\phpbb\db\driver\driver_interface $db, $table_prefix, array $config = array(), array $grantTypes = array(), array $responseTypes = array(), TokenTypeInterface $tokenType = null, ScopeInterface $scopeUtil = null, ClientAssertionTypeInterface $clientAssertionType = null)
    {
        $storage = new phpbb_storage($db, $table_prefix);
        parent::__construct($storage, $config, $grantTypes, $responseTypes, $tokenType, $scopeUtil, $clientAssertionType); // TODO: Change the autogenerated stub
    }


}
